sonar.projectKey=Forge-Space_siza-desktop
sonar.organization=forge-space
sonar.projectName=siza-desktop

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,src/**/test-setup.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.test.ts,**/*.test.tsx,src/**/test-setup.ts
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,src/**/test-setup.ts,src/**/*.d.ts
sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx,src/**/test-setup.ts
