sonar.projectKey=Forge-Space_siza-desktop
sonar.organization=forge-space
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,src/**/test-setup.ts
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,src/**/test-setup.ts,src/**/*.d.ts
sonar.exclusions=**/*.test.ts,**/*.test.tsx,src/**/test-setup.ts,**/node_modules/**
sonar.typescript.lcov.reportPaths=coverage/coverage-final.json
sonar.typescript.nodejs.projectRoot=.
