name: Secret Scanning

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v6
      - name: TruffleHog OSS (pull request)
        if: github.event_name == 'pull_request'
        uses: trufflesecurity/trufflehog@6171fa9f6676edf21e15bba41f049b18399d7372
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --only-verified --results=verified
      - name: TruffleHog OSS (push or schedule)
        if: github.event_name != 'pull_request'
        uses: trufflesecurity/trufflehog@6171fa9f6676edf21e15bba41f049b18399d7372
        with:
          path: ./
          extra_args: --only-verified --results=verified
